// <auto-generated />
using BooksAppAPI.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksAppAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230114220533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksAppAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lent")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            Lent = false,
                            Title = "Book 1",
                            Year = 2001
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            Lent = true,
                            Title = "Book 2",
                            Year = 2002
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            Lent = false,
                            Title = "Book 3",
                            Year = 2003
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            Lent = true,
                            Title = "Book 4",
                            Year = 2004
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            Lent = false,
                            Title = "Book 5",
                            Year = 2005
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            Lent = true,
                            Title = "Book 6",
                            Year = 2006
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            Lent = false,
                            Title = "Book 7",
                            Year = 2007
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 8",
                            Lent = true,
                            Title = "Book 8",
                            Year = 2008
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 9",
                            Lent = false,
                            Title = "Book 9",
                            Year = 2009
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 10",
                            Lent = true,
                            Title = "Book 10",
                            Year = 2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
