// <auto-generated />
using System;
using BooksAppAPI.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksAppAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksAppAPI.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lent")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("362c6052-3fad-4f31-89bd-b9384a469df1"),
                            Author = "Author 01",
                            Lent = false,
                            Title = "Book 01",
                            Year = 2001
                        },
                        new
                        {
                            Id = new Guid("96f98c22-bc6e-48c0-9d01-833571cb8dcd"),
                            Author = "Author 02",
                            Lent = true,
                            Title = "Book 02",
                            Year = 2002
                        },
                        new
                        {
                            Id = new Guid("50765f55-4f78-4995-b575-ea7de3ed6799"),
                            Author = "Author 03",
                            Lent = false,
                            Title = "Book 03",
                            Year = 2003
                        },
                        new
                        {
                            Id = new Guid("066acf19-6f1e-4005-bb1e-98e4258a12ff"),
                            Author = "Author 04",
                            Lent = true,
                            Title = "Book 04",
                            Year = 2004
                        },
                        new
                        {
                            Id = new Guid("f39e6d05-f6e6-49fb-a995-f3bb9507d903"),
                            Author = "Author 05",
                            Lent = false,
                            Title = "Book 05",
                            Year = 2005
                        },
                        new
                        {
                            Id = new Guid("7bad80d8-8dba-4102-a053-39d4fa4d3160"),
                            Author = "Author 06",
                            Lent = true,
                            Title = "Book 06",
                            Year = 2006
                        },
                        new
                        {
                            Id = new Guid("d36daa61-2418-4240-9bb4-c1cbaf2e1592"),
                            Author = "Author 07",
                            Lent = false,
                            Title = "Book 07",
                            Year = 2007
                        },
                        new
                        {
                            Id = new Guid("160042ef-06a4-4691-98c0-5258abfb0e27"),
                            Author = "Author 08",
                            Lent = true,
                            Title = "Book 08",
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("766bb44e-17c6-4b30-be61-af3ea05be518"),
                            Author = "Author 09",
                            Lent = false,
                            Title = "Book 09",
                            Year = 2009
                        },
                        new
                        {
                            Id = new Guid("e92639c3-81d2-4624-bf17-c7e75632a834"),
                            Author = "Author 10",
                            Lent = true,
                            Title = "Book 10",
                            Year = 2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
